In [1]:
from alphagenome import colab_utils
from alphagenome.data import gene_annotation, genome, track_data, transcript
from alphagenome.models import dna_client
from alphagenome.visualization import plot_components
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

/home1/smaruj/envs/alphagenome/lib/python3.11/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.27.2 is exactly one major version older than the runtime version 6.31.1 at alphagenome/protos/dna_model.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/home1/smaruj/envs/alphagenome/lib/python3.11/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.27.2 is exactly one major version older than the runtime version 6.31.1 at alphagenome/protos/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
/home1/smaruj/envs/alphagenome/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
api_key = "AIzaSyBh9ICxEr8WOH63OELhl13TtqI1xvNo6LY"

In [3]:
# default alphagenome model
dna_model = dna_client.create(api_key)

In [4]:
dna_model.output_metadata().concatenate()

,name,strand,Assay title,ontology_curie,biosample_name,biosample_type,biosample_life_stage,data_source,endedness,genetically_modified,nonzero_mean,output_type,gtex_tissue,histone_mark,transcription_factor
0,CL:0000084 ATAC-seq,.,ATAC-seq,CL:0000084,T-cell,primary_cell,adult,encode,paired,False,0.739741,OutputType.ATAC,NaN,NaN,NaN
1,CL:0000100 ATAC-seq,.,ATAC-seq,CL:0000100,motor neuron,in_vitro_differentiated_cells,adult,encode,paired,False,0.273136,OutputType.ATAC,NaN,NaN,NaN
2,CL:0000236 ATAC-seq,.,ATAC-seq,CL:0000236,B cell,primary_cell,adult,encode,paired,False,4.700081,OutputType.ATAC,NaN,NaN,NaN
3,CL:0000623 ATAC-seq,.,ATAC-seq,CL:0000623,natural killer cell,primary_cell,adult,encode,paired,False,0.938715,OutputType.ATAC,NaN,NaN,NaN
4,CL:0000624 ATAC-seq,.,ATAC-seq,CL:0000624,"CD4-positive, alpha-beta T cell",primary_cell,adult,encode,paired,False,4.365206,OutputType.ATAC,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,ENCSR182QNJ,-,PRO-cap,EFO:0001099,Caco-2,cell_line,NaN,encode,NaN,False,14.002803,OutputType.PROCAP,NaN,NaN,NaN
8,ENCSR740IPL,-,PRO-cap,EFO:0002067,K562,cell_line,NaN,encode,NaN,False,15.765458,OutputType.PROCAP,NaN,NaN,NaN
9,ENCSR797DEF,-,PRO-cap,EFO:0002819,Calu3,cell_line,NaN,encode,NaN,False,12.281321,OutputType.PROCAP,NaN,NaN,NaN
10,ENCSR801ECP,-,PRO-cap,CL:0002618,endothelial cell of umbilical vein,primary_cell,NaN,encode,NaN,False,13.973692,OutputType.PROCAP,NaN,NaN,NaN
11,ENCSR860TYZ,-,PRO-cap,EFO:0001200,MCF 10A,cell_line,NaN,encode,NaN,False,8.229502,OutputType.PROCAP,NaN,NaN,NaN

In [5]:
FOLD = 0

In [6]:
flat_regions_path = f"/scratch1/smaruj/genomic_flat_regions/flat_regions_chrom_states_tsv/fold{FOLD}_selected_genomic_windows_centered_chrom_states.tsv"

In [7]:
df = pd.read_csv(flat_regions_path, sep="\t")

In [8]:
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
def plot_map(matrix, vmin=-0.6, vmax=0.6, palette="RdBu_r", width=5, height=5):
    fig, axes = plt.subplots(1, 1, figsize=(width, height))

    sns.heatmap(
        matrix,
        vmin=vmin,
        vmax=vmax,
        cbar=False,
        cmap=palette,
        square=True,
        xticklabels=False,
        yticklabels=False,
        ax=axes
    )

    plt.tight_layout()
    plt.show()

In [10]:
def read_fasta_to_string(fasta_path: str) -> str:
    """Read a (single-record) FASTA file and return the sequence as one string."""
    seq_lines = []
    with open(fasta_path) as f:
        for line in f:
            if line.startswith(">"):
                continue
            seq_lines.append(line.strip())
    return "".join(seq_lines).upper()

In [11]:
og_fasta_dir = f"/scratch1/smaruj/alpha_genome_validation/original_sequences/fold{FOLD}_original"

In [12]:
og_flame_mean_values = []

H, W = (512, 512)
half_r, half_c = H // 2, W // 2
flame_width=3

half_flame_width = flame_width // 2

for i, row in enumerate(df.itertuples(index=False)):
    print(i)
    chrom, start, end = row.chrom, row.centered_start, row.centered_end
    fasta_path = f"{og_fasta_dir}/{chrom}_{start}_{end}.fasta"
    
    seq = read_fasta_to_string(fasta_path)
    
    output = dna_model.predict_sequence(
        organism=dna_client.Organism.MUS_MUSCULUS,
        sequence=seq,
        requested_outputs=[dna_client.OutputType.CONTACT_MAPS],
        ontology_terms=['EFO:0004038'] # mESC
    )
    
    matrix = output.contact_maps.values[:,:,0]
    
    # plot_map(matrix)
    
    flame_mean = np.nanmean(matrix[:half_r, half_c - half_flame_width:half_c + half_flame_width])
    og_flame_mean_values.append(flame_mean)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45

In [13]:
df

,chrom,fold,PearsonR,centered_start,centered_end,centered_flat_start,centered_flat_end,active_fraction,neutral_fraction,repressive_fraction
0,chr1,fold0,0.861165,37799936,39110656,192,320,0.391304,0.521739,0.086957
1,chr11,fold0,0.746112,65677312,66988032,195,317,0.333333,0.533333,0.133333
2,chr3,fold0,0.670098,38524928,39835648,144,368,0.483871,0.516129,0.000000
3,chr3,fold0,0.672787,53286912,54597632,187,325,0.360000,0.520000,0.120000
4,chr3,fold0,0.676442,119885824,121196544,154,358,0.500000,0.500000,0.000000
5,chr3,fold0,0.681364,101859328,103170048,202,310,0.371429,0.514286,0.114286
6,chr3,fold0,0.684073,99010560,100321280,163,349,0.476190,0.523810,0.000000
7,chr3,fold0,0.690577,80795648,82106368,159,353,0.473684,0.526316,0.000000
8,chr3,fold0,0.700263,127893504,129204224,190,322,0.444444,0.555556,0.000000
9,chr3,fold0,0.750709,146692096,148002816,134,378,0.444444,0.518519,0.037037
10,chr3,fold0,0.754782,40724480,42035200,206,306,0.263158,0.526316,0.210526
11,chr3,fold0,0.773129,136558592,137869312,128,384,0.473684,0.500000,0.026316
12,chr3,fold0,0.774494,152809472,154120192,193,319,0.303030,0.515152,0.181818
13,chr3,fold0,0.776279,105613312,106924032,199,313,0.482759,0.517241,0.000000
14,chr3,fold0,0.798202,135677952,136988672,196,316,0.285714,0.571429,0.142857
15,chr3,fold0,0.827614,134367232,135677952,200,312,0.444444,0.555556,0.000000
16,chr3,fold0,0.833280,128325632,129636352,193,319,0.454545,0.545455,0.000000
17,chr3,fold0,0.855747,51949568,53260288,172,340,0.439024,0.512195,0.048780
18,chr4,fold0,0.668603,127655936,128966656,184,328,0.448980,0.510204,0.040816
19,chr4,fold0,0.719536,103120896,104431616,202,310,0.444444,0.555556,0.000000
20,chr4,fold0,0.750432,109963264,111273984,182,330,0.333333,0.533333,0.133333
21,chr4,fold0,0.769843,104028160,105338880,184,328,0.142857,0.571429,0.285714
22,chr4,fold0,0.790109,95809536,97120256,183,329,0.450000,0.500000,0.050000
23,chr4,fold0,0.828356,95033344,96344064,198,314,0.333333,0.555556,0.111111
24,chr4,fold0,0.885081,152287232,153597952,195,317,0.303030,0.515152,0.181818
25,chr5,fold0,0.660858,97062912,98373632,181,331,0.428571,0.571429,0.000000
26,chr5,fold0,0.662273,95946752,97257472,202,310,0.473684,0.526316,0.000000
27,chr5,fold0,0.678001,85061632,86372352,191,321,0.333333,0.666667,0.000000
28,chr5,fold0,0.679395,48887808,50198528,204,308,0.333333,0.555556,0.111111
29,chr5,fold0,0.704619,91060224,92370944,184,328,0.391304,0.521739,0.086957
30,chr5,fold0,0.707673,97955840,99266560,163,349,0.480000,0.520000,0.000000
31,chr5,fold0,0.711089,45426688,46737408,178,334,0.444444,0.555556,0.000000
32,chr5,fold0,0.724697,82620416,83931136,204,308,0.428571,0.571429,0.000000
33,chr5,fold0,0.733389,96688128,97998848,185,327,0.320000,0.520000,0.160000
34,chr5,fold0,0.734416,36800512,38111232,205,307,0.285714,0.523810,0.190476
35,chr5,fold0,0.742412,51138560,52449280,187,325,0.444444,0.555556,0.000000
36,chr5,fold0,0.743897,62668800,63979520,157,355,0.483871,0.516129,0.000000
37,chr5,fold0,0.767142,41830400,43141120,181,331,0.470588,0.529412,0.000000
38,chr5,fold0,0.776065,44417024,45727744,186,326,0.500000,0.500000,0.000000
39,chr5,fold0,0.788813,38354944,39665664,174,338,0.440000,0.520000,0.040000
40,chr5,fold0,0.792530,98772992,100083712,200,312,0.466667,0.533333,0.000000
41,chr6,fold0,0.661027,65536000,66846720,193,319,0.480000,0.520000,0.000000
42,chr6,fold0,0.687477,61061120,62371840,186,326,0.200000,0.600000,0.200000
43,chrX,fold0,0.708108,46925824,48236544,187,325,0.454545,0.545455,0.000000
44,chrX,fold0,0.752140,60768256,62078976,173,339,0.473684,0.526316,0.000000
45,chrX,fold0,0.816017,48441344,49752064,191,321,0.428571,0.571429,0.000000

In [14]:
df["alpha_og_flame_score"] = og_flame_mean_values

In [15]:
mod_fasta_dir = f"/scratch1/smaruj/alpha_genome_validation/flame_generation/fold{FOLD}_modified"

In [16]:
mod_flame_mean_values = []

for i, row in enumerate(df.itertuples(index=False)):
    print(i)
    chrom, start, end = row.chrom, row.centered_start, row.centered_end
    fasta_path = f"{mod_fasta_dir}/{chrom}_{start}_{end}.fasta"
    
    seq = read_fasta_to_string(fasta_path)
    
    output = dna_model.predict_sequence(
        organism=dna_client.Organism.MUS_MUSCULUS,
        sequence=seq,
        requested_outputs=[dna_client.OutputType.CONTACT_MAPS],
        ontology_terms=['EFO:0004038'] # mESC
    )
    
    matrix = output.contact_maps.values[:,:,0]
    # plot_map(matrix)
    
    flame_mean = np.nanmean(matrix[:half_r, half_c - half_flame_width:half_c + half_flame_width])
    mod_flame_mean_values.append(flame_mean)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45

In [17]:
df["alpha_ed_flame_score"] = mod_flame_mean_values

In [18]:
df["alpha_flame_score_diff"] = df["alpha_ed_flame_score"] - df["alpha_og_flame_score"]

In [19]:
df

,chrom,fold,PearsonR,centered_start,centered_end,centered_flat_start,centered_flat_end,active_fraction,neutral_fraction,repressive_fraction,alpha_og_flame_score,alpha_ed_flame_score,alpha_flame_score_diff
0,chr1,fold0,0.861165,37799936,39110656,192,320,0.391304,0.521739,0.086957,-0.227714,0.541600,0.769314
1,chr11,fold0,0.746112,65677312,66988032,195,317,0.333333,0.533333,0.133333,0.073855,0.596619,0.522764
2,chr3,fold0,0.670098,38524928,39835648,144,368,0.483871,0.516129,0.000000,-0.130888,0.382268,0.513157
3,chr3,fold0,0.672787,53286912,54597632,187,325,0.360000,0.520000,0.120000,-0.124200,0.642951,0.767151
4,chr3,fold0,0.676442,119885824,121196544,154,358,0.500000,0.500000,0.000000,-0.013494,-0.013494,0.000000
5,chr3,fold0,0.681364,101859328,103170048,202,310,0.371429,0.514286,0.114286,-0.044944,0.674725,0.719669
6,chr3,fold0,0.684073,99010560,100321280,163,349,0.476190,0.523810,0.000000,0.146034,0.557182,0.411148
7,chr3,fold0,0.690577,80795648,82106368,159,353,0.473684,0.526316,0.000000,0.153506,0.468135,0.314629
8,chr3,fold0,0.700263,127893504,129204224,190,322,0.444444,0.555556,0.000000,-0.078233,0.598324,0.676557
9,chr3,fold0,0.750709,146692096,148002816,134,378,0.444444,0.518519,0.037037,-0.049299,0.462912,0.512210
10,chr3,fold0,0.754782,40724480,42035200,206,306,0.263158,0.526316,0.210526,-0.101943,0.660133,0.762077
11,chr3,fold0,0.773129,136558592,137869312,128,384,0.473684,0.500000,0.026316,-0.025417,0.359993,0.385410
12,chr3,fold0,0.774494,152809472,154120192,193,319,0.303030,0.515152,0.181818,0.209313,0.559046,0.349733
13,chr3,fold0,0.776279,105613312,106924032,199,313,0.482759,0.517241,0.000000,-0.154631,-0.154631,0.000000
14,chr3,fold0,0.798202,135677952,136988672,196,316,0.285714,0.571429,0.142857,0.134894,0.569794,0.434900
15,chr3,fold0,0.827614,134367232,135677952,200,312,0.444444,0.555556,0.000000,0.173779,0.173779,0.000000
16,chr3,fold0,0.833280,128325632,129636352,193,319,0.454545,0.545455,0.000000,0.139629,0.373116,0.233487
17,chr3,fold0,0.855747,51949568,53260288,172,340,0.439024,0.512195,0.048780,0.031404,0.526898,0.495494
18,chr4,fold0,0.668603,127655936,128966656,184,328,0.448980,0.510204,0.040816,0.255257,0.578466,0.323209
19,chr4,fold0,0.719536,103120896,104431616,202,310,0.444444,0.555556,0.000000,0.002671,0.617224,0.614553
20,chr4,fold0,0.750432,109963264,111273984,182,330,0.333333,0.533333,0.133333,0.030890,0.030890,0.000000
21,chr4,fold0,0.769843,104028160,105338880,184,328,0.142857,0.571429,0.285714,-0.032859,0.329886,0.362745
22,chr4,fold0,0.790109,95809536,97120256,183,329,0.450000,0.500000,0.050000,0.174442,0.643310,0.468868
23,chr4,fold0,0.828356,95033344,96344064,198,314,0.333333,0.555556,0.111111,0.138032,0.490607,0.352575
24,chr4,fold0,0.885081,152287232,153597952,195,317,0.303030,0.515152,0.181818,-0.025214,0.605140,0.630354
25,chr5,fold0,0.660858,97062912,98373632,181,331,0.428571,0.571429,0.000000,-0.115325,0.265646,0.380971
26,chr5,fold0,0.662273,95946752,97257472,202,310,0.473684,0.526316,0.000000,0.004012,0.568584,0.564572
27,chr5,fold0,0.678001,85061632,86372352,191,321,0.333333,0.666667,0.000000,-0.006582,-0.006582,0.000000
28,chr5,fold0,0.679395,48887808,50198528,204,308,0.333333,0.555556,0.111111,-0.186263,0.324600,0.510863
29,chr5,fold0,0.704619,91060224,92370944,184,328,0.391304,0.521739,0.086957,-0.013070,0.474276,0.487346
30,chr5,fold0,0.707673,97955840,99266560,163,349,0.480000,0.520000,0.000000,-0.094840,0.565465,0.660305
31,chr5,fold0,0.711089,45426688,46737408,178,334,0.444444,0.555556,0.000000,-0.028622,0.539500,0.568123
32,chr5,fold0,0.724697,82620416,83931136,204,308,0.428571,0.571429,0.000000,0.113302,0.261224,0.147922
33,chr5,fold0,0.733389,96688128,97998848,185,327,0.320000,0.520000,0.160000,-0.167412,0.477913,0.645325
34,chr5,fold0,0.734416,36800512,38111232,205,307,0.285714,0.523810,0.190476,-0.354393,0.336525,0.690917
35,chr5,fold0,0.742412,51138560,52449280,187,325,0.444444,0.555556,0.000000,0.066135,0.271527,0.205392
36,chr5,fold0,0.743897,62668800,63979520,157,355,0.483871,0.516129,0.000000,0.155616,0.155616,0.000000
37,chr5,fold0,0.767142,41830400,43141120,181,331,0.470588,0.529412,0.000000,-0.075546,-0.075546,0.000000
38,chr5,fold0,0.776065,44417024,45727744,186,326,0.500000,0.500000,0.000000,0.058054,0.306828,0.248774
39,chr5,fold0,0.788813,38354944,39665664,174,338,0.440000,0.520000,0.040000,-0.307053,0.359434,0.666487
40,chr5,fold0,0.792530,98772992,100083712,200,312,0.466667,0.533333,0.000000,-0.137431,0.376086,0.513516
41,chr6,fold0,0.661027,65536000,66846720,193,319,0.480000,0.520000,0.000000,0.025210,0.348911,0.323701
42,chr6,fold0,0.687477,61061120,62371840,186,326,0.200000,0.600000,0.200000,-0.010305,-0.010305,0.000000
43,chrX,fold0,0.708108,46925824,48236544,187,325,0.454545,0.545455,0.000000,-0.058793,0.252038,0.310830
44,chrX,fold0,0.752140,60768256,62078976,173,339,0.473684,0.526316,0.000000,-0.248762,0.334961,0.583724
45,chrX,fold0,0.816017,48441344,49752064,191,321,0.428571,0.571429,0.000000,0.039043,0.714096,0.675053

In [20]:
df.to_csv(f"/scratch1/smaruj/alpha_genome_validation/flame_generation/fold{FOLD}_alphagenome_results.tsv", sep="\t", index=False)