In [1]:
from alphagenome import colab_utils
from alphagenome.data import gene_annotation, genome, track_data, transcript
from alphagenome.models import dna_client
from alphagenome.visualization import plot_components
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
api_key = "AIzaSyBh9ICxEr8WOH63OELhl13TtqI1xvNo6LY"

In [3]:
# default alphagenome model
dna_model = dna_client.create(api_key)

In [4]:
dna_model.output_metadata().concatenate()

,name,strand,Assay title,ontology_curie,biosample_name,biosample_type,biosample_life_stage,data_source,endedness,genetically_modified,nonzero_mean,output_type,gtex_tissue,histone_mark,transcription_factor
0,CL:0000084 ATAC-seq,.,ATAC-seq,CL:0000084,T-cell,primary_cell,adult,encode,paired,False,0.739741,OutputType.ATAC,NaN,NaN,NaN
1,CL:0000100 ATAC-seq,.,ATAC-seq,CL:0000100,motor neuron,in_vitro_differentiated_cells,adult,encode,paired,False,0.273136,OutputType.ATAC,NaN,NaN,NaN
2,CL:0000236 ATAC-seq,.,ATAC-seq,CL:0000236,B cell,primary_cell,adult,encode,paired,False,4.700081,OutputType.ATAC,NaN,NaN,NaN
3,CL:0000623 ATAC-seq,.,ATAC-seq,CL:0000623,natural killer cell,primary_cell,adult,encode,paired,False,0.938715,OutputType.ATAC,NaN,NaN,NaN
4,CL:0000624 ATAC-seq,.,ATAC-seq,CL:0000624,"CD4-positive, alpha-beta T cell",primary_cell,adult,encode,paired,False,4.365206,OutputType.ATAC,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,ENCSR182QNJ,-,PRO-cap,EFO:0001099,Caco-2,cell_line,NaN,encode,NaN,False,14.002803,OutputType.PROCAP,NaN,NaN,NaN
8,ENCSR740IPL,-,PRO-cap,EFO:0002067,K562,cell_line,NaN,encode,NaN,False,15.765458,OutputType.PROCAP,NaN,NaN,NaN
9,ENCSR797DEF,-,PRO-cap,EFO:0002819,Calu3,cell_line,NaN,encode,NaN,False,12.281321,OutputType.PROCAP,NaN,NaN,NaN
10,ENCSR801ECP,-,PRO-cap,CL:0002618,endothelial cell of umbilical vein,primary_cell,NaN,encode,NaN,False,13.973692,OutputType.PROCAP,NaN,NaN,NaN
11,ENCSR860TYZ,-,PRO-cap,EFO:0001200,MCF 10A,cell_line,NaN,encode,NaN,False,8.229502,OutputType.PROCAP,NaN,NaN,NaN

In [5]:
FOLD = 0

In [6]:
flat_regions_path = f"/scratch1/smaruj/generate_cell_type_specific_features/fold{FOLD}_HUMAN_selected_genomic_windows_centered.tsv"

In [7]:
df = pd.read_csv(flat_regions_path, sep="\t")

In [8]:
df = df[:43]

In [9]:
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
def plot_map(matrix, vmin=-0.6, vmax=0.6, palette="RdBu_r", width=5, height=5):
    fig, axes = plt.subplots(1, 1, figsize=(width, height))

    sns.heatmap(
        matrix,
        vmin=vmin,
        vmax=vmax,
        cbar=False,
        cmap=palette,
        square=True,
        xticklabels=False,
        yticklabels=False,
        ax=axes
    )

    plt.tight_layout()
    plt.show()

In [11]:
def read_fasta_to_string(fasta_path: str) -> str:
    """Read a (single-record) FASTA file and return the sequence as one string."""
    seq_lines = []
    with open(fasta_path) as f:
        for line in f:
            if line.startswith(">"):
                continue
            seq_lines.append(line.strip())
    return "".join(seq_lines).upper()

In [12]:
og_fasta_dir = f"/scratch1/smaruj/alpha_genome_validation/cell_type_specific_boundary/fold{FOLD}_original"

In [13]:
og_urq_mean_values = []

for i, row in enumerate(df.itertuples(index=False)):
    print(i)
    chrom, start, end = row.chrom, row.centered_start, row.centered_end
    fasta_path = f"{og_fasta_dir}/{chrom}_{start}_{end}.fasta"
    
    seq = read_fasta_to_string(fasta_path)
    
    output = dna_model.predict_sequence(
        organism=dna_client.Organism.HOMO_SAPIENS,
        sequence=seq,
        requested_outputs=[dna_client.OutputType.CONTACT_MAPS],
        # ontology_terms=['EFO:0003042'] #H1-hESC
        ontology_terms=['EFO:0002824'] #HCT116
    )
    
    matrix = output.contact_maps.values[:,:,0]
    
    # plot_map(matrix)
    
    urq_mean = np.nanmean(matrix[0:250, 260:512])
    og_urq_mean_values.append(urq_mean)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42

In [14]:
df["alpha_og_urq"] = og_urq_mean_values

In [15]:
mod_fasta_dir = f"/scratch1/smaruj/alpha_genome_validation/cell_type_specific_boundary/H1hESC_weak_HCT116_strong_results"

In [16]:
mod_urq_mean_values = []

for i, row in enumerate(df.itertuples(index=False)):
    print(i)
    chrom, start, end = row.chrom, row.centered_start, row.centered_end
    fasta_path = f"{mod_fasta_dir}/{chrom}_{start}_{end}.fasta"
    
    seq = read_fasta_to_string(fasta_path)
    
    output = dna_model.predict_sequence(
        organism=dna_client.Organism.HOMO_SAPIENS,
        sequence=seq,
        requested_outputs=[dna_client.OutputType.CONTACT_MAPS],
        # ontology_terms=['EFO:0003042'] #H1-hESC
        ontology_terms=['EFO:0002824'] #HCT116
    )
    
    matrix = output.contact_maps.values[:,:,0]
    # plot_map(matrix)
    
    urq_mean = np.nanmean(matrix[0:250, 260:512])
    mod_urq_mean_values.append(urq_mean)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42

In [17]:
df["alpha_ed_urq"] = mod_urq_mean_values

In [18]:
df["alpha_urq_diff"] = df["alpha_ed_urq"] - df["alpha_og_urq"]

In [19]:
df

,chrom,start,end,fold,PearsonR,flat_start,flat_end,centered_start,centered_end,centered_flat_start,centered_flat_end,alpha_og_urq,alpha_ed_urq,alpha_urq_diff
0,chr1,3119104,4429824,fold0,0.689834,354.0,455.0,3422208,4732928,206,306,-0.223669,-0.444549,-0.220879
1,chr1,28999680,30310400,fold0,0.797276,306.0,439.0,29237248,30547968,190,322,0.366431,0.146420,-0.220011
2,chr1,33079296,34390016,fold0,0.854244,244.0,420.0,33234944,34545664,168,344,0.152524,-0.157135,-0.309659
3,chr1,36028416,37339136,fold0,0.870734,298.0,398.0,36216832,37527552,206,306,0.216304,-0.039131,-0.255435
4,chr1,37666816,38977536,fold0,0.820790,150.0,284.0,37586944,38897664,189,323,-0.023934,-0.270947,-0.247012
5,chr1,40943616,42254336,fold0,0.714602,307.0,455.0,41199616,42510336,182,330,0.058360,-0.204072,-0.262432
6,chr1,49387520,50698240,fold0,0.859766,83.0,208.0,49160192,50470912,194,318,0.293937,0.065566,-0.228371
7,chr1,58562560,59873280,fold0,0.669620,75.0,264.0,58384384,59695104,162,350,0.150502,-0.240690,-0.391192
8,chr1,59545600,60856320,fold0,0.867924,327.0,455.0,59822080,61132800,192,320,0.340657,-0.060326,-0.400982
9,chr1,68065280,69376000,fold0,0.847200,221.0,455.0,68233216,69543936,139,373,0.157254,-0.190557,-0.347811
10,chr1,69048320,70359040,fold0,0.704915,56.0,239.0,68825088,70135808,165,347,0.271300,0.001221,-0.270079
11,chr1,76277760,77588480,fold0,0.732832,56.0,324.0,76142592,77453312,122,390,0.200795,0.029257,-0.171538
12,chr1,78571520,79882240,fold0,0.679109,95.0,215.0,78364672,79675392,196,316,0.086543,-0.296807,-0.383350
13,chr1,78899200,80209920,fold0,0.712134,254.0,455.0,79099904,80410624,156,356,0.230741,-0.217732,-0.448474
14,chr1,86765568,88076288,fold0,0.865363,246.0,455.0,86958080,88268800,152,360,0.317649,-0.115004,-0.432652
15,chr1,87748608,89059328,fold0,0.741386,155.0,260.0,87648256,88958976,204,308,-0.090968,-0.332632,-0.241664
16,chr1,89387008,90697728,fold0,0.754323,331.0,455.0,89667584,90978304,194,318,-0.053651,-0.333668,-0.280016
17,chr1,94957568,96268288,fold0,0.677789,210.0,455.0,95113216,96423936,134,378,0.240499,0.141811,-0.098688
18,chr1,97906688,99217408,fold0,0.741776,56.0,179.0,97622016,98932736,195,317,0.061138,-0.261640,-0.322778
19,chr1,98234368,99545088,fold0,0.774748,233.0,366.0,98322432,99633152,190,322,0.115367,-0.175634,-0.291001
20,chr1,101183488,102494208,fold0,0.761800,146.0,308.0,101124096,102434816,175,337,0.045065,-0.189656,-0.234721
21,chr1,111341568,112652288,fold0,0.886589,178.0,362.0,111370240,112680960,164,348,-0.063368,-0.293710,-0.230342
22,chr1,117567488,118878208,fold0,0.760917,299.0,455.0,117815296,119126016,178,334,0.349016,-0.073340,-0.422356
23,chr11,57528320,58839040,fold0,0.757874,114.0,264.0,57391104,58701824,181,331,0.057223,-0.291670,-0.348892
24,chr13,33366016,34676736,fold0,0.751517,316.0,455.0,33630208,34940928,187,325,0.206086,-0.160220,-0.366305
25,chr13,36642816,37953536,fold0,0.818498,200.0,374.0,36706304,38017024,169,343,0.013448,-0.353419,-0.366866
26,chr13,39591936,40902656,fold0,0.720495,245.0,347.0,39673856,40984576,205,307,0.269563,-0.168219,-0.437781
27,chr2,102397952,103708672,fold0,0.713333,338.0,455.0,102684672,103995392,198,314,0.241176,-0.026741,-0.267916
28,chr4,6621184,7931904,fold0,0.742950,261.0,442.0,6815744,8126464,166,346,0.089242,-0.151357,-0.240599
29,chr4,10135552,11446272,fold0,0.809684,264.0,455.0,10346496,11657216,161,351,0.325958,-0.020600,-0.346559
30,chr4,11773952,13084672,fold0,0.675996,94.0,259.0,11610112,12920832,174,338,0.316556,-0.014287,-0.330843
31,chr4,12756992,14067712,fold0,0.828519,125.0,236.0,12601344,13912064,201,311,0.151206,-0.213445,-0.364652
32,chr4,13084672,14395392,fold0,0.832009,249.0,415.0,13240320,14551040,173,339,-0.037317,-0.317495,-0.280179
33,chr4,16361472,17672192,fold0,0.706727,166.0,376.0,16392192,17702912,151,361,0.217972,-0.193211,-0.411183
34,chr4,18327552,19638272,fold0,0.814980,233.0,341.0,18391040,19701760,202,310,0.154641,-0.155071,-0.309713
35,chr4,19638272,20948992,fold0,0.740150,56.0,199.0,19374080,20684800,185,327,0.146919,-0.130709,-0.277627
36,chr4,22390784,23701504,fold0,0.692599,332.0,455.0,22671360,23982080,195,317,0.239314,0.007949,-0.231364
37,chr4,23373824,24684544,fold0,0.848279,124.0,415.0,23400448,24711168,111,401,0.171956,-0.153354,-0.325310
38,chr4,27305984,28616704,fold0,0.777714,161.0,455.0,27412480,28723200,109,403,0.122322,-0.189022,-0.311343
39,chr4,36521984,37832704,fold0,0.817264,56.0,236.0,36296704,37607424,166,346,0.276787,-0.068605,-0.345392
40,chr4,43730944,45041664,fold0,0.737712,56.0,249.0,43517952,44828672,160,352,0.262706,-0.090812,-0.353518
41,chr4,44386304,45697024,fold0,0.681080,233.0,426.0,44535808,45846528,160,352,0.181124,-0.144423,-0.325547
42,chr4,66459648,67770368,fold0,0.804096,66.0,214.0,66222080,67532800,182,330,0.122111,-0.167007,-0.289118

In [20]:
df.to_csv(f"/scratch1/smaruj/alpha_genome_validation/cell_type_specific_boundary/H1hESC_weak_HCT116_strong_HTC116_alphagenome_results.tsv", sep="\t", index=False)