In [1]:
from alphagenome import colab_utils
from alphagenome.data import gene_annotation, genome, track_data, transcript
from alphagenome.models import dna_client
from alphagenome.visualization import plot_components
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
api_key = "AIzaSyBh9ICxEr8WOH63OELhl13TtqI1xvNo6LY"

In [3]:
# default alphagenome model
dna_model = dna_client.create(api_key)

In [4]:
dna_model.output_metadata().concatenate()

,name,strand,Assay title,ontology_curie,biosample_name,biosample_type,biosample_life_stage,data_source,endedness,genetically_modified,nonzero_mean,output_type,gtex_tissue,histone_mark,transcription_factor
0,CL:0000084 ATAC-seq,.,ATAC-seq,CL:0000084,T-cell,primary_cell,adult,encode,paired,False,0.739741,OutputType.ATAC,NaN,NaN,NaN
1,CL:0000100 ATAC-seq,.,ATAC-seq,CL:0000100,motor neuron,in_vitro_differentiated_cells,adult,encode,paired,False,0.273136,OutputType.ATAC,NaN,NaN,NaN
2,CL:0000236 ATAC-seq,.,ATAC-seq,CL:0000236,B cell,primary_cell,adult,encode,paired,False,4.700081,OutputType.ATAC,NaN,NaN,NaN
3,CL:0000623 ATAC-seq,.,ATAC-seq,CL:0000623,natural killer cell,primary_cell,adult,encode,paired,False,0.938715,OutputType.ATAC,NaN,NaN,NaN
4,CL:0000624 ATAC-seq,.,ATAC-seq,CL:0000624,"CD4-positive, alpha-beta T cell",primary_cell,adult,encode,paired,False,4.365206,OutputType.ATAC,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,ENCSR182QNJ,-,PRO-cap,EFO:0001099,Caco-2,cell_line,NaN,encode,NaN,False,14.002803,OutputType.PROCAP,NaN,NaN,NaN
8,ENCSR740IPL,-,PRO-cap,EFO:0002067,K562,cell_line,NaN,encode,NaN,False,15.765458,OutputType.PROCAP,NaN,NaN,NaN
9,ENCSR797DEF,-,PRO-cap,EFO:0002819,Calu3,cell_line,NaN,encode,NaN,False,12.281321,OutputType.PROCAP,NaN,NaN,NaN
10,ENCSR801ECP,-,PRO-cap,CL:0002618,endothelial cell of umbilical vein,primary_cell,NaN,encode,NaN,False,13.973692,OutputType.PROCAP,NaN,NaN,NaN
11,ENCSR860TYZ,-,PRO-cap,EFO:0001200,MCF 10A,cell_line,NaN,encode,NaN,False,8.229502,OutputType.PROCAP,NaN,NaN,NaN

In [5]:
FOLD = 2

In [6]:
flat_regions_path = f"/scratch1/smaruj/genomic_flat_regions/flat_regions_chrom_states_tsv/fold{FOLD}_selected_genomic_windows_centered_chrom_states.tsv"

In [7]:
df = pd.read_csv(flat_regions_path, sep="\t")

In [8]:
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
def read_fasta_to_string(fasta_path: str) -> str:
    """Read a (single-record) FASTA file and return the sequence as one string."""
    seq_lines = []
    with open(fasta_path) as f:
        for line in f:
            if line.startswith(">"):
                continue
            seq_lines.append(line.strip())
    return "".join(seq_lines).upper()

In [10]:
og_fasta_dir = f"/scratch1/smaruj/suppressing_CTCFs/alphagenome_CTCF_ChIPseq/original_sequences/fold{FOLD}_original"

In [11]:
start_editable_region = 4096 - 8
end_editable_region   = 4096 + 8

In [12]:
og_signal_sum_values = []

for i, row in enumerate(df.itertuples(index=False)):
    print(i)
    chrom, start, end = row.chrom, row.centered_start, row.centered_end
    fasta_path = f"{og_fasta_dir}/{chrom}_{start}_{end}.fasta"
    
    seq = read_fasta_to_string(fasta_path)
    
    output = dna_model.predict_sequence(
        organism=dna_client.Organism.MUS_MUSCULUS,
        sequence=seq,
        requested_outputs=[dna_client.OutputType.CHIP_TF],
        ontology_terms=['CL:2000042'] # CTCF ChiP-seq
    )
    
    track = output.chip_tf.values[:,0]
    
    signal_sum = np.sum(track[start_editable_region:end_editable_region])
    # print(signal_sum)
    og_signal_sum_values.append(signal_sum)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57

In [13]:
df["alpha_og_CTCF_ChIPseq_sum"] = og_signal_sum_values

In [14]:
mod_fasta_dir = f"/scratch1/smaruj/suppressing_CTCFs/alphagenome_CTCF_ChIPseq/modified_sequences/fold{FOLD}_modified"

In [15]:
mod_signal_sum_values = []

for i, row in enumerate(df.itertuples(index=False)):
    print(i)
    chrom, start, end = row.chrom, row.centered_start, row.centered_end
    fasta_path = f"{mod_fasta_dir}/{chrom}_{start}_{end}.fasta"
    
    seq = read_fasta_to_string(fasta_path)
    
    output = dna_model.predict_sequence(
        organism=dna_client.Organism.MUS_MUSCULUS,
        sequence=seq,
        requested_outputs=[dna_client.OutputType.CHIP_TF],
        ontology_terms=['CL:2000042'] # CTCF ChiP-seq
    )
    
    track = output.chip_tf.values[:,0]
    
    signal_sum = np.sum(track[start_editable_region:end_editable_region])
    # print(signal_sum)
    mod_signal_sum_values.append(signal_sum)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57

In [16]:
df["alpha_mod_CTCF_ChIPseq_sum"] = mod_signal_sum_values

In [17]:
df

,chrom,fold,PearsonR,centered_start,centered_end,centered_flat_start,centered_flat_end,active_fraction,neutral_fraction,repressive_fraction,alpha_og_CTCF_ChIPseq_sum,alpha_mod_CTCF_ChIPseq_sum
0,chr11,fold2,0.732358,45981696,47292416,194,318,0.222222,0.555556,0.222222,2615.250000,3287.125000
1,chr11,fold2,0.767461,56039424,57350144,173,339,0.440000,0.520000,0.040000,2710.750000,2555.125000
2,chr11,fold2,0.791830,39716864,41027584,192,320,0.444444,0.555556,0.000000,1963.250000,4265.000000
3,chr11,fold2,0.833249,42188800,43499520,171,341,0.466667,0.533333,0.000000,602.500000,500.375000
4,chr11,fold2,0.836212,44619776,45930496,170,342,0.428571,0.523810,0.047619,5895.500000,3361.750000
5,chr11,fold2,0.910790,55146496,56457216,190,322,0.411765,0.529412,0.058824,4554.187500,6489.750000
6,chr11,fold2,0.915895,43421696,44732416,160,352,0.411765,0.529412,0.058824,8259.875000,5335.375000
7,chr14,fold2,0.731114,10399744,11710464,168,344,0.382353,0.500000,0.117647,5653.250000,4894.500000
8,chr14,fold2,0.738000,11220992,12531712,187,325,0.157895,0.526316,0.315789,5245.000000,4979.250000
9,chr14,fold2,0.763067,17168384,18479104,204,308,0.428571,0.571429,0.000000,2138.562500,2297.625000
10,chr14,fold2,0.800507,12353536,13664256,187,325,0.444444,0.518519,0.037037,5836.875000,2753.937500
11,chr14,fold2,0.834629,32135168,33445888,197,315,0.200000,0.533333,0.266667,7345.812500,6003.875000
12,chr14,fold2,0.892145,34529280,35840000,161,351,0.461538,0.500000,0.038462,7019.812500,11128.125000
13,chr16,fold2,0.728675,27633664,28944384,205,307,0.333333,0.666667,0.000000,4096.250000,3898.500000
14,chr16,fold2,0.737162,83501056,84811776,126,386,0.421053,0.526316,0.052632,5014.125000,3072.000000
15,chr16,fold2,0.740622,86013952,87324672,179,333,0.444444,0.555556,0.000000,927.562500,1097.500000
16,chr16,fold2,0.740803,62771200,64081920,142,370,0.454545,0.545455,0.000000,610.625000,610.625000
17,chr16,fold2,0.756053,55816192,57126912,165,347,0.352941,0.529412,0.117647,2989.617188,2791.911133
18,chr16,fold2,0.762520,84725760,86036480,189,323,0.384615,0.538462,0.076923,3422.500000,4207.875000
19,chr16,fold2,0.779459,57339904,58650624,166,346,0.476190,0.523810,0.000000,2466.375000,2466.375000
20,chr16,fold2,0.786068,75931648,77242368,201,311,0.454545,0.515152,0.030303,925.625000,923.375000
21,chr16,fold2,0.791533,25088000,26398720,185,327,0.333333,0.555556,0.111111,639.812500,657.625000
22,chr16,fold2,0.802980,23521280,24832000,196,316,0.400000,0.600000,0.000000,954.937500,1061.625000
23,chr16,fold2,0.803004,87361536,88672256,197,315,0.363636,0.545455,0.090909,5744.250000,6653.875000
24,chr16,fold2,0.815385,28428288,29739008,206,306,0.380952,0.523810,0.095238,7213.875000,9933.500000
25,chr16,fold2,0.822493,41957376,43268096,195,317,0.391304,0.521739,0.086957,8916.250000,14356.250000
26,chr16,fold2,0.828908,23068672,24379392,202,310,0.476190,0.523810,0.000000,904.750000,777.250000
27,chr16,fold2,0.833438,92489728,93800448,205,307,0.483871,0.483871,0.032258,3074.125000,2293.000000
28,chr16,fold2,0.840454,85454848,86765568,180,332,0.466667,0.533333,0.000000,4979.750000,3970.500000
29,chr17,fold2,0.819204,29601792,30912512,188,324,0.137931,0.517241,0.344828,3939.062500,2526.750000
30,chr18,fold2,0.773994,83652608,84963328,181,331,0.307692,0.538462,0.153846,5642.750000,5594.000000
31,chr3,fold2,0.751825,72771584,74082304,150,362,0.482759,0.517241,0.000000,1829.000000,1808.625000
32,chr3,fold2,0.763637,31385600,32696320,204,308,0.470588,0.529412,0.000000,3910.750000,1798.750000
33,chr3,fold2,0.769086,69746688,71057408,142,370,0.461538,0.538462,0.000000,6883.250000,8024.812500
34,chr3,fold2,0.795049,64485376,65796096,173,339,0.307692,0.538462,0.153846,5879.375000,4360.250000
35,chr3,fold2,0.801535,33613824,34924544,197,315,0.428571,0.500000,0.071429,4131.375000,2513.375000
36,chr3,fold2,0.819141,29609984,30920704,167,345,0.333333,0.666667,0.000000,6489.000000,4498.625000
37,chr6,fold2,0.729222,102365184,103675904,192,320,0.333333,0.666667,0.000000,806.625000,806.625000
38,chr6,fold2,0.754648,73232384,74543104,194,318,0.444444,0.555556,0.000000,3254.000000,5074.500000
39,chr6,fold2,0.765494,80910336,82221056,181,331,0.470588,0.529412,0.000000,4408.875000,2965.875000
40,chr6,fold2,0.775228,95879168,97189888,159,353,0.444444,0.500000,0.055556,5253.625000,3795.000000
41,chr6,fold2,0.800588,92551168,93861888,159,353,0.440000,0.520000,0.040000,7275.125000,5553.500000
42,chr6,fold2,0.801597,98617344,99928064,166,346,0.105263,0.526316,0.368421,1402.875000,1402.875000
43,chr6,fold2,0.801666,91858944,93169664,202,310,0.266667,0.533333,0.200000,1203.125000,1144.250000
44,chr6,fold2,0.856989,89509888,90820608,205,307,0.461538,0.500000,0.038462,4500.000000,2425.750000
45,chr6,fold2,0.866654,99411968,100722688,201,311,0.250000,0.500000,0.250000,6527.000000,5731.625000
46,chr6,fold2,0.896686,116738048,118048768,175,337,0.441176,0.500000,0.058824,821.382812,845.000000
47,chr7,fold2,0.728496,84496384,85807104,178,334,0.483871,0.516129,0.000000,800.875000,1115.406250
48,chr7,fold2,0.745462,75452416,76763136,194,318,0.480000,0.520000,0.000000,2454.609375,1575.328125
49,chr7,fold2,0.772271,66351104,67661824,204,308,0.470588,0.529412,0.000000,4929.375000,6758.375000
50,chr7,fold2,0.885965,72183808,73494528,187,325,0.461538,0.538462,0.000000,3408.000000,4967.750000
51,chr9,fold2,0.792664,104148992,105459712,173,339,0.485714,0.514286,0.000000,8028.000000,10140.500000
52,chr9,fold2,0.832669,111067136,112377856,197,315,0.440000,0.520000,0.040000,7675.125000,5337.875000
53,chr9,fold2,0.841365,101357568,102668288,121,391,0.460317,0.507937,0.031746,4468.750000,5109.750000
54,chr9,fold2,0.843037,96993280,98304000,104,408,0.473684,0.508772,0.017544,4370.000000,7700.000000
55,chr9,fold2,0.846394,112386048,113696768,187,325,0.444444,0.500000,0.055556,5850.000000,4030.250000
56,chr9,fold2,0.890602,94369792,95680512,171,341,0.466667,0.533333,0.000000,797.750000,797.750000
57,chr9,fold2,0.903110,99528704,100839424,184,328,0.482759,0.517241,0.000000,868.750000,911.937500

In [18]:
df.to_csv(f"/scratch1/smaruj/suppressing_CTCFs/alphagenome_CTCF_ChIPseq/fold{FOLD}_alphagenome_results.tsv", sep="\t", index=False)